nefive:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    head_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: chest_box_head_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    head_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_pan_head_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}