nefive:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    head_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: chest_box_head_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    head_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_pan_head_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    right_arm_right_shoulder_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_arm_right_shoulder_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_shoulder_tilt_right_shoulder_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_shoulder_tilt_right_shoulder_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_shoulder_pan_right_shoulder_rotate_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_shoulder_pan_right_shoulder_rotate_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_shoulder_rotate_right_elbow_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_shoulder_rotate_right_elbow_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_forearm_right_wrist_roll_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_forearm_right_wrist_roll_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_wrist_roll_right_wrist_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_wrist_roll_right_wrist_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    right_wrist_tilt_right_wrist_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_wrist_tilt_right_wrist_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_arm_left_shoulder_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_arm_left_shoulder_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_shoulder_tilt_left_shoulder_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_shoulder_tilt_left_shoulder_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_shoulder_pan_left_shoulder_rotate_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_shoulder_pan_left_shoulder_rotate_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_shoulder_rotate_left_elbow_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_shoulder_rotate_left_elbow_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_forearm_left_wrist_roll_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_forearm_left_wrist_roll_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_wrist_roll_left_wrist_tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_wrist_roll_left_wrist_tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    left_wrist_tilt_left_wrist_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_wrist_tilt_left_wrist_pan_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}


















